# DATABASE OPERATION FUNCTIONS (CRUD & Core Helpers)
# This module implements all database queries and transactions (Create, Read,
# Update, Delete) using SQLAlchemy's asynchronous interface.
# These functions decouple raw database logic from the API routers.

import hashlib
import random
import secrets
import string
from datetime import datetime, timezone, date, timedelta

from fastapi import HTTPException
from fastapi import status as http_status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, update, delete
from sqlalchemy.orm import selectinload

# Import tables/models from our db module
from src.utils.db import (
    User, Caller, CallLog, AgentSettings, Order,
    MenuCategory, MenuItem, MenuSpecial,
)


# 1. USER AUTHENTICATION QUERIES

async def get_user_by_email(db: AsyncSession, email: str) -> User | None:
    """
    Looks up a User in the database by their unique email address.
    Returns the User object if found, otherwise returns None.
    """
    # select(User) represents "SELECT * FROM users"
    # .where(...) filters rows where User.email matches the search parameter
    result = await db.execute(select(User).where(User.email == email))
    # .scalar_one_or_none() returns the single User record, or None if empty
    return result.scalar_one_or_none()


async def get_user_by_id(db: AsyncSession, user_id: str) -> User | None:
    """
    Looks up a User by their unique primary key ID.
    """
    result = await db.execute(select(User).where(User.id == user_id))
    return result.scalar_one_or_none()


async def create_user(db: AsyncSession, email: str, hashed_password: str, full_name: str) -> User:
    """
    Registers a new admin dashboard User in the database.
    """
    # 1. Instantiate the SQLAlchemy Model
    user = User(email=email, hashed_password=hashed_password, full_name=full_name, is_admin=True)
    # 2. Add to the session transaction unit-of-work
    db.add(user)
    # 3. Write changes to the physical PostgreSQL database
    await db.commit()
    # 4. Refresh properties (loads autogenerated ID, default created_at times, etc.)
    await db.refresh(user)
    return user


async def update_reset_token(db: AsyncSession, user_id: str, token: str, expires: datetime) -> None:
    """
    Saves a hashed password reset token and expiration time for a user.
    """
    # For security, we never store the raw reset token. We hash it with SHA-256 first.
    hashed = hashlib.sha256(token.encode()).hexdigest()
    await db.execute(
        update(User)
        .where(User.id == user_id)
        .values(reset_token=hashed, reset_token_expires=expires)
    )
    await db.commit()


async def clear_reset_token(db: AsyncSession, user_id: str) -> None:
    """
    Clears reset token properties from a user's account after a password reset completes.
    """
    await db.execute(
        update(User).where(User.id == user_id).values(reset_token=None, reset_token_expires=None)
    )
    await db.commit()


async def update_password(db: AsyncSession, user_id: str, hashed_password: str) -> None:
    """
    Updates the hashed password of a user.
    """
    await db.execute(
        update(User).where(User.id == user_id).values(hashed_password=hashed_password)
    )
    await db.commit()


# 2. CALLER & CUSTOMER HISTORY QUERIES

def normalize_phone_number(phone: str) -> str:
    """
    Helper to normalize phone numbers by extracting digits only
    and returning the last 10 characters to bypass formatting mismatches.
    """
    if not phone:
        return ""
    digits = "".join(c for c in phone if c.isdigit())
    return digits[-10:] if len(digits) >= 10 else digits


async def get_caller_by_phone(db: AsyncSession, phone_number: str) -> Caller | None:
    """
    Retrieves Caller contact records using their E.164 phone number.
    Supports robust fallback matching by normalized phone suffix.
    """
    if not phone_number:
        return None
    # 1. First attempt exact match
    result = await db.execute(select(Caller).where(Caller.phone_number == phone_number))
    caller = result.scalar_one_or_none()
    if caller:
        return caller

    # 2. Robust fallback matching by last 10 digits
    norm = normalize_phone_number(phone_number)
    if len(norm) >= 10:
        result = await db.execute(
            select(Caller).where(Caller.phone_number.like(f"%{norm}"))
        )
        return result.scalars().first()
    return None


async def upsert_caller(db: AsyncSession, phone_number: str, customer_name: str | None) -> Caller:
    """
    Upsert pattern (Insert or Update):
    Finds a caller by phone number. If they do not exist, inserts a new one.
    If they exist and lack a saved name, updates their name.
    """
    caller = await get_caller_by_phone(db, phone_number)
    if caller is None:
        # Create a new record if new caller
        caller = Caller(phone_number=phone_number, customer_name=customer_name)
        db.add(caller)
    elif customer_name and not caller.customer_name:
        # Update name if we just discovered it
        caller.customer_name = customer_name
    await db.commit()
    await db.refresh(caller)
    return caller


async def update_caller_last_called(db: AsyncSession, phone_number: str) -> None:
    """
    Updates the timestamp of the last call received from a caller.
    """
    await db.execute(
        update(Caller)
        .where(Caller.phone_number == phone_number)
        .values(last_called_at=datetime.now(timezone.utc))
    )
    await db.commit()


# 3. CALL LOGGING & DIALOGUE METRICS

async def create_call_log(
    db: AsyncSession,
    call_id: str,
    caller_phone: str,
    customer_name: str | None,
    direction: str,
    call_status: str,
) -> CallLog:
    """
    Creates a new CallLog row to monitor a phone call session.
    """
    log = CallLog(
        call_id=call_id,
        caller_phone=caller_phone,
        customer_name=customer_name,
        direction=direction,
        call_status=call_status,
    )
    db.add(log)
    await db.commit()
    await db.refresh(log)
    return log


async def update_call_log(db: AsyncSession, call_id: str, **kwargs) -> None:
    """
    Updates a call log's columns dynamically.
    **kwargs: Accepts keyword arguments matching table column names (e.g. transcript="hello", duration_ms=200).
    """
    await db.execute(
        update(CallLog).where(CallLog.call_id == call_id).values(**kwargs)
    )
    await db.commit()


async def get_call_log_by_call_id(db: AsyncSession, call_id: str) -> CallLog | None:
    """
    Fetches a call log and its associated order details.
    
    Why 'selectinload':
    SQLAlchemy avoids loading related models (like Order details) by default to save memory.
    Using '.options(selectinload(CallLog.order_details))' forces SQLAlchemy to load the
    Order associated with the call log in a single transaction, avoiding LazyLoading errors.
    """
    result = await db.execute(
        select(CallLog)
        .options(selectinload(CallLog.order_details))
        .where(CallLog.call_id == call_id)
    )
    return result.scalar_one_or_none()


async def list_call_logs(
    db: AsyncSession,
    skip: int,
    limit: int,
    status_filter: str | None,
    order_booked_filter: bool | None,
) -> list[CallLog]:
    """
    Lists calls with pagination (skip, limit) and optional filters.
    """
    query = (
        select(CallLog)
        .options(selectinload(CallLog.order_details))
        .order_by(CallLog.created_at.desc())
    )
    # Conditionally add filter requirements to the SQL query statement
    if status_filter is not None:
        query = query.where(CallLog.call_status == status_filter)
    if order_booked_filter is not None:
        query = query.where(CallLog.order_booked == order_booked_filter)

    # Apply pagination AFTER filters so it operates on the filtered set
    query = query.offset(skip).limit(limit)

    result = await db.execute(query)
    # Return a clean list of row models
    return list(result.scalars().all())


async def get_combined_stats(db: AsyncSession) -> dict:
    """
    Compiles calls and orders overview metrics for dashboard status badges.
    """
    total_calls = await db.scalar(select(func.count()).select_from(CallLog)) or 0
    successful_calls = await db.scalar(select(func.count()).select_from(CallLog).where(CallLog.call_successful == True)) or 0
    failed_calls = await db.scalar(select(func.count()).select_from(CallLog).where(CallLog.call_successful == False)) or 0
    pending_calls = await db.scalar(select(func.count()).select_from(CallLog).where(CallLog.call_successful == None)) or 0
    order_stats = await get_order_stats(db)

    # Compute today's calls in the restaurant's local timezone (Asia/Karachi)
    try:
        from zoneinfo import ZoneInfo
        settings_row = await db.execute(select(AgentSettings).limit(1))
        _settings = settings_row.scalar_one_or_none()
        tz_name = (_settings.restaurant_timezone if _settings else None) or "Asia/Karachi"
        tz = ZoneInfo(tz_name)
    except Exception:
        from datetime import timezone as _tz
        tz = _tz.utc

    now_local = datetime.now(tz)
    today_local_start = now_local.replace(hour=0, minute=0, second=0, microsecond=0)
    today_local_end = today_local_start + timedelta(days=1)
    today_utc_start = today_local_start.astimezone(timezone.utc)
    today_utc_end = today_local_end.astimezone(timezone.utc)

    today_calls = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= today_utc_start,
            CallLog.created_at < today_utc_end,
        )
    ) or 0
    today_inbound_calls = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= today_utc_start,
            CallLog.created_at < today_utc_end,
            func.lower(CallLog.direction) == "inbound",
        )
    ) or 0
    today_outbound_calls = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= today_utc_start,
            CallLog.created_at < today_utc_end,
            func.lower(CallLog.direction) == "outbound",
        )
    ) or 0

    return {
        "calls": {
            "total": total_calls,
            "successful": successful_calls,
            "failed": failed_calls,
            "pending": pending_calls,
            "today": today_calls,
            "today_inbound": today_inbound_calls,
            "today_outbound": today_outbound_calls,
        },
        "orders": order_stats,
    }


# 4. AGENT VOICE & BUSINESS SETTINGS

async def get_agent_settings(db: AsyncSession) -> AgentSettings:
    """
    Retrieves the global agent settings configuration row.
    If no settings row exists yet, inserts a default one.
    """
    result = await db.execute(select(AgentSettings).limit(1))
    settings = result.scalar_one_or_none()
    if settings is None:
        settings = AgentSettings()
        db.add(settings)
        await db.commit()
        await db.refresh(settings)
    return settings


async def update_agent_settings(db: AsyncSession, **kwargs) -> AgentSettings:
    """
    Updates global agent settings properties.
    """
    settings = await get_agent_settings(db)
    for key, value in kwargs.items():
        setattr(settings, key, value)
    settings.updated_at = datetime.now(timezone.utc)
    await db.commit()
    await db.refresh(settings)
    return settings


# 5. INVENTORY & CATEGORIES CRUD

async def create_category(
    db: AsyncSession, name: str, description: str | None, sort_order: int
) -> MenuCategory:
    """
    Creates a new product category in the menu database.
    """
    category = MenuCategory(name=name, description=description, sort_order=sort_order)
    db.add(category)
    await db.commit()
    await db.refresh(category)
    return category


async def list_categories(db: AsyncSession) -> list[MenuCategory]:
    """
    Returns all product categories sorted by sort_order.
    """
    result = await db.execute(select(MenuCategory).order_by(MenuCategory.sort_order.asc()))
    return list(result.scalars().all())


async def get_category(db: AsyncSession, category_id: str) -> MenuCategory | None:
    """
    Fetches a single menu category record.
    """
    result = await db.execute(select(MenuCategory).where(MenuCategory.id == category_id))
    return result.scalar_one_or_none()


async def update_category(db: AsyncSession, category_id: str, **kwargs) -> MenuCategory:
    """
    Updates menu category attributes.
    """
    category = await get_category(db, category_id)
    if not category:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Category not found")
    await db.execute(update(MenuCategory).where(MenuCategory.id == category_id).values(**kwargs))
    await db.commit()
    return await get_category(db, category_id)


async def delete_category(db: AsyncSession, category_id: str) -> None:
    """
    Deletes a category if it doesn't contain any products.
    """
    items = await list_items(db, category_id=category_id)
    if items:
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Remove all items from this category before deleting it.",
        )
    await db.execute(delete(MenuCategory).where(MenuCategory.id == category_id))
    await db.commit()


# 6. MENU PRODUCTS CRUD

async def create_item(
    db: AsyncSession,
    category_id: str,
    name: str,
    description: str | None,
    price: float,
    is_available: bool,
    allergens: str | None,
    prep_time_minutes: int | None,
    sort_order: int,
) -> MenuItem:
    """
    Creates a new product item linked to a category.
    """
    category = await get_category(db, category_id)
    if not category:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Category not found")
    item = MenuItem(
        category_id=category_id,
        name=name,
        description=description,
        price=price,
        is_available=is_available,
        allergens=allergens,
        prep_time_minutes=prep_time_minutes,
        sort_order=sort_order,
    )
    db.add(item)
    await db.commit()
    await db.refresh(item)
    return item


async def list_items(db: AsyncSession, category_id: str | None = None) -> list[MenuItem]:
    """
    Lists product items, optionally filtered by category.
    """
    query = select(MenuItem).order_by(MenuItem.sort_order.asc())
    if category_id is not None:
        query = query.where(MenuItem.category_id == category_id)
    result = await db.execute(query)
    return list(result.scalars().all())


async def get_item(db: AsyncSession, item_id: str) -> MenuItem | None:
    """
    Fetches a single product item by ID.
    """
    result = await db.execute(select(MenuItem).where(MenuItem.id == item_id))
    return result.scalar_one_or_none()


async def update_item(db: AsyncSession, item_id: str, **kwargs) -> MenuItem:
    """
    Updates menu item attributes.
    """
    item = await get_item(db, item_id)
    if not item:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Item not found")
    kwargs["updated_at"] = datetime.now(timezone.utc)
    await db.execute(update(MenuItem).where(MenuItem.id == item_id).values(**kwargs))
    await db.commit()
    return await get_item(db, item_id)


async def delete_item(db: AsyncSession, item_id: str) -> None:
    """
    Deletes a menu item by ID.
    """
    item = await get_item(db, item_id)
    if not item:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Item not found")
    await db.execute(delete(MenuItem).where(MenuItem.id == item_id))
    await db.commit()


# 7. PROMOTIONAL SPECIALS CRUD

async def create_special(
    db: AsyncSession,
    title: str,
    description: str,
    discount_type: str,
    discount_value: float | None,
    applicable_items: str | None,
    valid_from: datetime | None,
    valid_until: datetime | None,
    is_active: bool,
) -> MenuSpecial:
    """
    Registers a new promotional special deal.
    """
    special = MenuSpecial(
        title=title,
        description=description,
        discount_type=discount_type,
        discount_value=discount_value,
        applicable_items=applicable_items,
        valid_from=valid_from,
        valid_until=valid_until,
        is_active=is_active,
    )
    db.add(special)
    await db.commit()
    await db.refresh(special)
    return special


async def list_specials(db: AsyncSession, active_only: bool = False) -> list[MenuSpecial]:
    """
    Lists promotional specials. If active_only=True, filters by validity dates and is_active flag.
    """
    query = select(MenuSpecial)
    if active_only:
        now = datetime.now(timezone.utc)
        query = query.where(
            MenuSpecial.is_active == True,
            (MenuSpecial.valid_from == None) | (MenuSpecial.valid_from <= now),
            (MenuSpecial.valid_until == None) | (MenuSpecial.valid_until >= now),
        )
    result = await db.execute(query)
    return list(result.scalars().all())


async def get_special(db: AsyncSession, special_id: str) -> MenuSpecial | None:
    """
    Fetches a single special deal by ID.
    """
    result = await db.execute(select(MenuSpecial).where(MenuSpecial.id == special_id))
    return result.scalar_one_or_none()


async def update_special(db: AsyncSession, special_id: str, **kwargs) -> MenuSpecial:
    """
    Updates special deal attributes.
    """
    special = await get_special(db, special_id)
    if not special:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Special not found")
    kwargs["updated_at"] = datetime.now(timezone.utc)
    await db.execute(update(MenuSpecial).where(MenuSpecial.id == special_id).values(**kwargs))
    await db.commit()
    return await get_special(db, special_id)


async def delete_special(db: AsyncSession, special_id: str) -> None:
    """
    Deletes a special deal by ID.
    """
    special = await get_special(db, special_id)
    if not special:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Special not found")
    await db.execute(delete(MenuSpecial).where(MenuSpecial.id == special_id))
    await db.commit()


# 8. CONVERSATIONAL GRAPH HELPER: MENU TEXT SERIALIZER

async def build_menu_text(db: AsyncSession) -> str:
    """
    Serializes active menu categories, items, and deals into a single text block.
    
    Why this is used:
    This text is injected directly into the Retell Voice Agent's context instructions
    so it knows exactly what products exist, their prices, and today's deals.
    """
    categories = await list_categories(db)
    available_categories = [c for c in categories if c.is_available]
    if not available_categories:
        return "Product catalog currently unavailable."
        
    lines = ["PRODUCT CATALOG"]
    has_any_item = False
    
    for category in available_categories:
        items = await list_items(db, category_id=category.id)
        available_items = [i for i in items if i.is_available]
        if not available_items:
            continue
        has_any_item = True
        lines.append(f"\n=== {category.name} ===")
        for item in available_items:
            line = f"- {item.name} — ${item.price:.2f}"
            if item.description:
                line += f" | {item.description}"
            if item.allergens:
                line += f" | Allergens: {item.allergens}"
            if item.prep_time_minutes:
                line += f" | Prep: {item.prep_time_minutes} min"
            lines.append(line)
            
    if not has_any_item:
        return "Product catalog currently unavailable."
        
    specials = await list_specials(db, active_only=True)
    if specials:
        lines.append("\nTODAY'S SPECIALS")
        for special in specials:
            line = f"- {special.title}: {special.description}"
            if special.discount_type == "percentage" and special.discount_value:
                target = f" on {special.applicable_items}" if special.applicable_items else ""
                line += f" ({int(special.discount_value)}% off{target})"
            elif special.discount_type == "fixed_amount" and special.discount_value:
                line += f" (${special.discount_value:.2f} off)"
            if special.valid_until:
                line += f", valid until {special.valid_until.strftime('%I:%M%p').lstrip('0')}"
            lines.append(line)
            
    return "\n".join(lines)


# 9. SALES ORDER PROCESSING

async def create_order(
    db: AsyncSession,
    caller_phone: str,
    customer_name: str,
    order_items: list,
    order_type: str,
    delivery_address: str | None,
    total_amount: float | None,
    special_notes: str | None,
    call_id: str | None = None,
) -> Order:
    """
    Creates an Order record and generates a unique, human-readable Order ID string.
    Example ID: ORD-20260526-ABCD
    """
    # 1. Generate Order ID using current date + 4 random uppercase characters
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    suffix = "".join(secrets.choice(string.ascii_uppercase) for _ in range(4))
    order_id = f"ORD-{date_str}-{suffix}"
    
    # 2. Instantiate and add the order model
    order = Order(
        order_id=order_id,
        call_id=call_id,
        caller_phone=caller_phone,
        customer_name=customer_name,
        order_items=order_items,
        order_type=order_type,
        delivery_address=delivery_address or None,
        total_amount=total_amount,
        status="received",
        special_notes=special_notes or None,
    )
    db.add(order)
    await db.commit()
    await db.refresh(order)
    return order


async def list_orders(
    db: AsyncSession,
    skip: int = 0,
    limit: int = 20,
    status_filter: str | None = None,
    date_filter: str | None = None,
) -> list[Order]:
    """
    Retrieves a paginated list of Orders.
    Allows filtering by status (e.g. 'received', 'completed') or by date.
    """
    # 1. Build the base query ordering orders by created_at in descending order (newest first)
    query = select(Order).order_by(Order.created_at.desc()).offset(skip).limit(limit)
    
    # 2. Optionally add status filtering
    if status_filter:
        query = query.where(Order.status == status_filter)
        
    # 3. Optionally add date filtering
    if date_filter:
        # Convert string to standard Python date object
        parsed = date.fromisoformat(date_filter)
        # Use func.date to extract the date portion from the timestamp column
        query = query.where(func.date(Order.created_at) == parsed)
        
    result = await db.execute(query)
    return list(result.scalars().all())


async def get_order_by_id(db: AsyncSession, order_id: str) -> Order | None:
    """
    Looks up a specific order by its human-readable Order ID (e.g. ORD-...).
    """
    result = await db.execute(select(Order).where(Order.order_id == order_id))
    return result.scalar_one_or_none()


async def get_order_by_call_id(db: AsyncSession, call_id: str) -> Order | None:
    """
    Retrieves the Order record associated with a specific telephone call ID.
    """
    result = await db.execute(select(Order).where(Order.call_id == call_id))
    return result.scalar_one_or_none()


async def update_order(db: AsyncSession, order_id: str, **kwargs) -> Order:
    """
    Updates specific attributes of an Order.
    """
    order = await get_order_by_id(db, order_id)
    if not order:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Order not found")
    kwargs["updated_at"] = datetime.now(timezone.utc)
    await db.execute(update(Order).where(Order.order_id == order_id).values(**kwargs))
    await db.commit()
    return await get_order_by_id(db, order_id)


async def get_order_stats(db: AsyncSession) -> dict:
    """
    Calculates sales order status distributions for the dashboard widgets.
    
    Why this does complex counts:
    To count "today's orders", we must look at the user's timezone settings
    to determine the correct local day boundary (which is different from UTC day start).
    """
    total = await db.scalar(select(func.count()).select_from(Order)) or 0
    received = await db.scalar(select(func.count()).select_from(Order).where(Order.status == "received")) or 0
    preparing = await db.scalar(select(func.count()).select_from(Order).where(Order.status == "preparing")) or 0
    ready = await db.scalar(select(func.count()).select_from(Order).where(Order.status == "ready")) or 0
    completed = await db.scalar(select(func.count()).select_from(Order).where(Order.status == "completed")) or 0
    cancelled = await db.scalar(select(func.count()).select_from(Order).where(Order.status == "cancelled")) or 0

    # Compute "today" in the restaurant's local timezone (Asia/Karachi)
    try:
        from zoneinfo import ZoneInfo
        settings_row = await db.execute(select(AgentSettings).limit(1))
        _settings = settings_row.scalar_one_or_none()
        tz_name = (_settings.restaurant_timezone if _settings else None) or "Asia/Karachi"
        tz = ZoneInfo(tz_name)
    except Exception:
        from datetime import timezone as _tz
        tz = _tz.utc

    now_local = datetime.now(tz)
    today_local_start = now_local.replace(hour=0, minute=0, second=0, microsecond=0)
    today_local_end = today_local_start + timedelta(days=1)
    
    # Convert local start and end bounds back to UTC for database query consistency
    today_utc_start = today_local_start.astimezone(timezone.utc)
    today_utc_end = today_local_end.astimezone(timezone.utc)

    today_orders_count = await db.scalar(
        select(func.count()).select_from(Order).where(
            Order.created_at >= today_utc_start,
            Order.created_at < today_utc_end,
        )
    ) or 0

    today_inbound_orders = await db.scalar(
        select(func.count()).select_from(Order)
        .join(CallLog, Order.call_id == CallLog.call_id)
        .where(
            Order.created_at >= today_utc_start,
            Order.created_at < today_utc_end,
            func.lower(CallLog.direction) == "inbound",
        )
    ) or 0
    today_outbound_orders = await db.scalar(
        select(func.count()).select_from(Order)
        .join(CallLog, Order.call_id == CallLog.call_id)
        .where(
            Order.created_at >= today_utc_start,
            Order.created_at < today_utc_end,
            func.lower(CallLog.direction) == "outbound",
        )
    ) or 0

    return {
        "total": total,
        "received": received,
        "preparing": preparing,
        "ready": ready,
        "completed": completed,
        "cancelled": cancelled,
        "today": today_orders_count,
        "today_inbound": today_inbound_orders,
        "today_outbound": today_outbound_orders,
    }


async def get_recent_order_for_caller(
    db: AsyncSession, caller_phone: str, minutes: int = 60
) -> Order | None:
    """
    Tries to find a recently submitted order for a caller (within the last N minutes)
    that has not been linked to a Call Log yet.
    
    Why this is needed:
    If the caller registers an order but hangsup before webhook events process,
    this helper matches the order to the call log using their phone number.
    """
    if not caller_phone:
        return None
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=minutes)
    
    # Normalize phone numbers by extracting digits only, matching the last 10 digits
    normalized_input = "".join(c for c in caller_phone if c.isdigit())
    if len(normalized_input) > 10:
        normalized_input = normalized_input[-10:]
        
    if not normalized_input:
        return None

    # Fetch orders in the last 60 minutes that lack a call ID link
    result = await db.execute(
        select(Order)
        .where(
            Order.call_id == None,
            Order.created_at >= cutoff,
        )
        .order_by(Order.created_at.desc())
    )
    orders = result.scalars().all()
    
    for order in orders:
        if not order.caller_phone:
            continue
        order_phone_digits = "".join(c for c in order.caller_phone if c.isdigit())
        if len(order_phone_digits) > 10:
            order_phone_digits = order_phone_digits[-10:]
        if order_phone_digits == normalized_input:
            return order
            
    return None


async def get_dashboard_stats(db: AsyncSession, days: int = 7) -> dict:
    """
    Compiles dashboard aggregate analytics reports for the last N days.
    Calculates total calls, total orders, call minutes, success rates, etc.
    """
    from datetime import datetime, timedelta, timezone
    from sqlalchemy import func, select
    from src.utils.db import CallLog, Order, Caller
    since = datetime.now(timezone.utc) - timedelta(days=days)
    
    orders_subquery = select(Order.call_id).where(Order.call_id.isnot(None)).subquery()
    unlinked_orders = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= since,
            CallLog.order_booked == True,
            CallLog.call_id.not_in(orders_subquery)
        )
    ) or 0

    total_calls = await db.scalar(select(func.count()).select_from(CallLog).where(CallLog.created_at >= since)) or 0
    total_orders = (await db.scalar(select(func.count()).select_from(Order).where(Order.created_at >= since)) or 0) + unlinked_orders
    total_minutes_ms = await db.scalar(
        select(func.sum(CallLog.duration_ms))
        .select_from(CallLog)
        .where(CallLog.created_at >= since)
        .where(CallLog.duration_ms.isnot(None))
    ) or 0
    # Convert duration from milliseconds to minutes
    total_minutes = round((total_minutes_ms or 0) / 60000, 1)
    successful_calls = await db.scalar(
        select(func.count())
        .select_from(CallLog)
        .where(CallLog.created_at >= since)
        .where(CallLog.call_successful == True)
    ) or 0
    
    # Subquery to calculate repeat caller rates
    subq = (
        select(CallLog.caller_phone)
        .where(CallLog.created_at >= since)
        .where(CallLog.caller_phone != "")
        .group_by(CallLog.caller_phone)
        .having(func.count() > 1)
        .subquery("sq")
    )
    repeat_callers = await db.scalar(select(func.count()).select_from(subq)) or 0
    new_callers = await db.scalar(select(func.count()).select_from(Caller).where(Caller.created_at >= since)) or 0
    
    # Pickup Order distributions
    pickup_orders_formal = await db.scalar(select(func.count()).select_from(Order).where(Order.created_at >= since).where(Order.order_type == "pickup")) or 0
    pickup_orders_draft = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= since,
            CallLog.order_booked == True,
            CallLog.order_type == "pickup",
            CallLog.call_id.not_in(orders_subquery)
        )
    ) or 0
    pickup_orders = pickup_orders_formal + pickup_orders_draft

    # Delivery Order distributions
    delivery_orders_formal = await db.scalar(select(func.count()).select_from(Order).where(Order.created_at >= since).where(Order.order_type == "delivery")) or 0
    delivery_orders_draft = await db.scalar(
        select(func.count()).select_from(CallLog).where(
            CallLog.created_at >= since,
            CallLog.order_booked == True,
            CallLog.order_type == "delivery",
            CallLog.call_id.not_in(orders_subquery)
        )
    ) or 0
    delivery_orders = delivery_orders_formal + delivery_orders_draft

    return {
        "total_calls": total_calls,
        "total_orders": total_orders,
        "total_minutes": total_minutes,
        "successful_calls": successful_calls,
        "repeat_callers": repeat_callers,
        "new_callers": new_callers,
        "order_type_distribution": {
            "pickup": pickup_orders,
            "delivery": delivery_orders,
        }
    }


async def get_calls_over_time(db: AsyncSession, days: int = 7) -> list:
    """
    Groups call volumes by day (SQL cast to Date) over the last N days.
    """
    from datetime import datetime, timedelta, timezone
    from sqlalchemy import func, select, cast, Date
    from src.utils.db import CallLog
    
    since = datetime.now(timezone.utc) - timedelta(days=days)
    result = await db.execute(
        select(cast(CallLog.created_at, Date).label("day"), func.count().label("calls"))
        .where(CallLog.created_at >= since)
        .group_by(cast(CallLog.created_at, Date))
        .order_by(cast(CallLog.created_at, Date))
    )
    rows = result.all()
    
    # Map dates to counts for easy dictionary retrieval
    date_map = {str(r.day): r.calls for r in rows}
    
    # Fill in potential missing days with 0 calls to keep chart plots uniform
    result_list = []
    for i in range(days):
        d = (datetime.now(timezone.utc) - timedelta(days=days - 1 - i)).date()
        result_list.append({"date": str(d), "calls": date_map.get(str(d), 0)})
    return result_list


async def get_orders_over_time(db: AsyncSession, days: int = 7) -> list:
    """
    Groups order volumes (formal orders and unlinked booked draft orders)
    by day over the last N days.
    """
    from datetime import datetime, timedelta, timezone
    from sqlalchemy import func, select, cast, Date
    from src.utils.db import Order, CallLog
    
    since = datetime.now(timezone.utc) - timedelta(days=days)
    
    # 1. Fetch formal orders count per day
    result_formal = await db.execute(
        select(cast(Order.created_at, Date).label("day"), func.count().label("orders"))
        .where(Order.created_at >= since)
        .group_by(cast(Order.created_at, Date))
    )
    formal_rows = result_formal.all()
    
    # 2. Fetch call-log unlinked draft orders count per day
    orders_subquery = select(Order.call_id).where(Order.call_id.isnot(None)).subquery()
    result_draft = await db.execute(
        select(cast(CallLog.created_at, Date).label("day"), func.count().label("orders"))
        .where(CallLog.created_at >= since)
        .where(CallLog.order_booked == True)
        .where(CallLog.call_id.not_in(orders_subquery))
        .group_by(cast(CallLog.created_at, Date))
    )
    draft_rows = result_draft.all()
    
    # 3. Merge date mappings
    date_map = {}
    for r in formal_rows:
        date_map[str(r.day)] = date_map.get(str(r.day), 0) + r.orders
    for r in draft_rows:
        date_map[str(r.day)] = date_map.get(str(r.day), 0) + r.orders
        
    # Fill in missing dates with 0 counts
    result_list = []
    for i in range(days):
        d = (datetime.now(timezone.utc) - timedelta(days=days - 1 - i)).date()
        result_list.append({"date": str(d), "orders": date_map.get(str(d), 0)})
    return result_list


async def get_top_repeat_callers(db: AsyncSession, days: int = 7, limit: int = 10) -> list:
    """
    Identifies phone numbers with multiple call log registrations over the last N days.
    """
    from datetime import datetime, timedelta, timezone
    from sqlalchemy import func, select
    from src.utils.db import CallLog
    
    since = datetime.now(timezone.utc) - timedelta(days=days)
    result = await db.execute(
        select(CallLog.caller_phone, CallLog.customer_name, func.count().label("call_count"))
        .where(CallLog.created_at >= since)
        .where(CallLog.caller_phone != "")
        .group_by(CallLog.caller_phone, CallLog.customer_name)
        .having(func.count() > 1)
        .order_by(func.count().desc())
        .limit(limit)
    )
    rows = result.all()
    return [
        {"phone": r.caller_phone, "name": r.customer_name or "Unknown", "call_count": r.call_count}
        for r in rows
    ]


async def get_sentiment_breakdown(db: AsyncSession, days: int = 7) -> dict:
    """
    Sums user sentiment classification results (e.g. positive, neutral, negative)
    returned from Retell AI analysis logs.
    """
    from datetime import datetime, timedelta, timezone
    from sqlalchemy import func, select
    from src.utils.db import CallLog
    
    since = datetime.now(timezone.utc) - timedelta(days=days)
    result = await db.execute(
        select(CallLog.user_sentiment, func.count().label("count"))
        .where(CallLog.created_at >= since)
        .where(CallLog.user_sentiment.isnot(None))
        .group_by(CallLog.user_sentiment)
    )
    rows = result.all()
    return {r.user_sentiment: r.count for r in rows}


# 10. CLOVER CLOUD MAPPING UTILITIES

async def get_clover_item_map(db: AsyncSession) -> dict[str, str]:
    """
    Returns a lookup dictionary mapping local product names to Clover IDs.
    """
    from src.utils.db import CloverItemMap
    result = await db.execute(
        select(CloverItemMap).where(CloverItemMap.is_active == True)
    )
    return {item.item_name: item.clover_item_id for item in result.scalars().all()}


async def upsert_clover_item(
    db: AsyncSession,
    item_name: str,
    clover_item_id: str,
    clover_item_name: str | None = None,
) -> None:
    """
    Saves or updates a name-to-clover-ID mapping definition.
    """
    from src.utils.db import CloverItemMap
    result = await db.execute(
        select(CloverItemMap).where(CloverItemMap.item_name == item_name)
    )
    existing = result.scalar_one_or_none()
    if existing:
        existing.clover_item_id = clover_item_id
        if clover_item_name:
            existing.clover_item_name = clover_item_name
        existing.updated_at = datetime.now(timezone.utc)
    else:
        db.add(CloverItemMap(
            item_name=item_name,
            clover_item_id=clover_item_id,
            clover_item_name=clover_item_name,
        ))
    await db.commit()


async def delete_clover_item(db: AsyncSession, item_name: str) -> None:
    """
    Deactivates (soft-deletes) a Clover mapping record by name.
    """
    from src.utils.db import CloverItemMap
    result = await db.execute(
        select(CloverItemMap).where(CloverItemMap.item_name == item_name)
    )
    existing = result.scalar_one_or_none()
    if existing:
        existing.is_active = False
        existing.updated_at = datetime.now(timezone.utc)
        await db.commit()


async def update_order_clover_status(
    db: AsyncSession,
    order_id: str,
    clover_order_id: str | None,
    synced: bool,
    error: str | None = None,
) -> None:
    """
    Saves Clover synchronization outcomes to the order record.
    If sync failed, writes the exception message to 'clover_error' for review.
    """
    from src.utils.db import Order
    await db.execute(
        update(Order)
        .where(Order.order_id == order_id)
        .values(clover_order_id=clover_order_id, clover_synced=synced, clover_error=error)
    )
    await db.commit()


async def get_menu_items_prices(db: AsyncSession, item_names: list[str]) -> dict[str, float]:
    """
    Helper to fetch product prices in bulk by name.
    Returns a lookup dictionary mapping lowercase names to float dollar prices.
    """
    if not item_names:
        return {}
    from src.utils.db import MenuItem
    result = await db.execute(
        select(MenuItem.name, MenuItem.price)
        .where(MenuItem.name.in_(item_names))
    )
    return {row[0].lower(): row[1] for row in result.all()}


# 11. CLOVER SYNC IMPLEMENTATION HELPERS

# Filter out internal/shipping/coupon items from menu syncs
CLOVER_ITEM_SKIP_PREFIXES = ("print", "gift card", "fb redeem", "waiver")


def _is_clover_internal_item(item: dict) -> bool:
    """
    Excludes free test cards or print service items from the customer catalog.
    """
    price_cents = item.get("price", 0)
    name = item.get("name", "").strip().lower()
    if price_cents == 0:
        return True
    if any(name.startswith(prefix) for prefix in CLOVER_ITEM_SKIP_PREFIXES):
        return True
    return False


async def upsert_menu_item_from_clover(db: AsyncSession, item: dict) -> bool:
    """
    Upserts a single product item returned by Clover POS into our database.
    Resolves the category and creates it if missing.
    """
    from src.utils.db import MenuItem, MenuCategory

    if _is_clover_internal_item(item):
        return False

    clover_id = item.get("id")
    name = item.get("name", "").strip()
    price_cents = item.get("price", 0)
    # Clover prices are in cents, convert back to float dollars (e.g. 350 cents -> 3.50 dollars)
    price = price_cents / 100.0
    hidden = item.get("hidden", False)

    # Determine category name from first category tag element
    cat_elements = item.get("categories", {}).get("elements", [])
    category_name = cat_elements[0].get("name", "Clover Items") if cat_elements else "Clover Items"

    # Find or insert Category
    cat_result = await db.execute(
        select(MenuCategory).where(MenuCategory.name == category_name)
    )
    category = cat_result.scalar_one_or_none()
    if not category:
        category = MenuCategory(name=category_name, is_available=True)
        db.add(category)
        await db.flush()  # flushes category properties to database to yield an autogenerated ID

    # Check for existing menu item by its clover ID
    item_result = await db.execute(
        select(MenuItem).where(MenuItem.clover_item_id == clover_id)
    )
    existing = item_result.scalar_one_or_none()

    now = datetime.now(timezone.utc)
    if existing:
        # Update existing details
        existing.name = name
        existing.price = price
        existing.category_id = category.id
        existing.is_available = not hidden
        existing.updated_at = now
    else:
        # Insert a new MenuItem row
        db.add(MenuItem(
            category_id=category.id,
            name=name,
            price=price,
            is_available=not hidden,
            clover_item_id=clover_id,
            created_at=now,
            updated_at=now,
        ))

    await db.commit()
    return True


async def full_sync_menu_from_clover(db: AsyncSession, clover_items: list[dict]) -> dict:
    """
    Wipes old manually-seeded records and synchronizes with current Clover items.
    
    Why this is used:
    Keeps the DB inventory identical to Clover. Disables missing items and drops empty categories.
    """
    from src.utils.db import MenuItem, MenuCategory
    from sqlalchemy import delete as sa_delete

    # 1. Clear old manually seeded items (items without clover IDs)
    await db.execute(
        sa_delete(MenuItem).where(MenuItem.clover_item_id.is_(None))
    )
    await db.commit()

    # 2. Temporarily set all clover menu items to unavailable
    await db.execute(
        update(MenuItem)
        .where(MenuItem.clover_item_id.is_not(None))
        .values(is_available=False, updated_at=datetime.now(timezone.utc))
    )
    await db.commit()

    # 3. Sync/re-enable items present in Clover
    synced = 0
    skipped = 0
    for item in clover_items:
        result = await upsert_menu_item_from_clover(db, item)
        if result:
            synced += 1
        else:
            skipped += 1

    # 4. Cleanup: Delete categories that have zero active/available items
    all_cats = (await db.execute(select(MenuCategory))).scalars().all()
    for cat in all_cats:
        # FIXED: Changed 'sa_func.count()' to 'func.count()' to resolve the NameError bug
        count = await db.scalar(
            select(func.count()).select_from(MenuItem).where(
                MenuItem.category_id == cat.id,
                MenuItem.is_available == True,
            )
        )
        if not count:
            await db.delete(cat)
    await db.commit()

    return {"synced": synced, "skipped": skipped}


async def delete_menu_item_by_clover_id(db: AsyncSession, clover_item_id: str) -> None:
    """
    Soft-deletes a menu item when Clover triggers a DELETE event.
    """
    from src.utils.db import MenuItem
    await db.execute(
        update(MenuItem)
        .where(MenuItem.clover_item_id == clover_item_id)
        .values(is_available=False, updated_at=datetime.now(timezone.utc))
    )
    await db.commit()


# 12. NATURAL LANGUAGE PROCESSING (NLP) TRANSCRIPT REGEX PARSER

async def auto_extract_order_items(
    db: AsyncSession,
    order_items_text: str,
    call_summary_text: str = "",
) -> list[dict]:
    """
    Parses conversational text transcripts to extract structured quantities
    matching products in our database.
    
    How this works:
      1. Combines transcript texts and loads all menu items.
      2. For each menu item, does case-insensitive lookups on singular/plural variations.
      3. Uses bidirectional regex search:
         - "qty before name" pattern: matches e.g. "3x Mango Jam" or "2 Mango Jam"
         - "qty after name" pattern: matches e.g. "Mango Jam: 2" or "Mango Jam (1)"
      4. Defaults item quantity count to 1 if no quantity indicator is nearby.
    """
    import re
    from src.utils.db import MenuItem

    # Combine summary and order text fields into a single searchable lowercase block
    combined = f"{order_items_text} {call_summary_text}".strip().lower()
    if not combined:
        return []

    # Get active catalog products
    result = await db.execute(
        select(MenuItem.name, MenuItem.price).where(MenuItem.is_available == True)
    )
    menu_rows = result.all()
    if not menu_rows:
        return []

    extracted: list[dict] = []
    seen_names: set[str] = set()

    for row_name, row_price in menu_rows:
        item_lower = row_name.lower().strip()
        matched = False
        matched_str = item_lower

        # Step A: String matching
        if item_lower in combined:
            matched = True
        # Step B: Plural check - if database name ends with 's', check for singular in text
        elif item_lower.endswith("s"):
            if item_lower.endswith("ies") and len(item_lower) > 3:
                singular = item_lower[:-3] + "y"
                if singular in combined:
                    matched = True
                    matched_str = singular
            elif item_lower.endswith("es") and len(item_lower) > 2:
                singular = item_lower[:-2]
                if singular in combined:
                    matched = True
                    matched_str = singular
            else:
                singular = item_lower[:-1]
                if singular in combined:
                    matched = True
                    matched_str = singular
        # Step C: Singular check - if database name ends with 'y', check for plural in text (e.g. jellies)
        elif item_lower.endswith("y") and len(item_lower) > 1:
            plural = item_lower[:-1] + "ies"
            if plural in combined:
                matched = True
                matched_str = plural

        if not matched:
            continue
        if item_lower in seen_names:
            continue
        seen_names.add(item_lower)

        escaped = re.escape(matched_str)
        qty = 1

        # Step D: Extract Quantity
        # 1. Search for quantity before item name (e.g. "3 Mango Jam" or "2 packs of Lemon Squash")
        m = re.search(r"(\d+)\s*(?:x|packs?|bags?|cases?|units?|bottles?|jars?|cartons?|tins?|boxes?|cans?)?\s*(?:of\s+)?(?:\b(?:the|a|an)\s+)?" + escaped, combined)
        if m:
            qty = int(m.group(1))
        else:
            # 2. Search for quantity after item name (e.g. "Mango Jam: 2" or "Golden Mist Marmalade (3)")
            m = re.search(escaped + r"\s*(?:x|×|:|\()\s*(\d+)", combined)
            if m:
                qty = int(m.group(1))

        # Append structured dictionary item
        extracted.append({
            "item": row_name,
            "quantity": qty,
            "price": row_price,
        })

    return extracted
